FROM library/mysql

ADD ./docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
##configure mysql
#ADD ./my.conf /etc/mysql/my.conf
##
#ADD ./setup_db.sh /scripts/
##
#CMD ["/bin/bash", "/scripts/setup_db.sh"]
